# Generated by Django 5.2.4 on 2025-07-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.ForeignKey(blank=True, help_text='Select the county where you are registered as a voter.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profiles.county'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_voted_before',
            field=models.BooleanField(blank=True, default=None, help_text='Let us know if you have voted before.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='knows_voting_process',
            field=models.BooleanField(blank=True, default=None, help_text='Tell us if you understand how voting works.', null=True),
        ),
    ]
