# Generated by Django 5.2.4 on 2025-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_userprofile_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wants_bill_notifications',
            field=models.BooleanField(blank=True, default=None, help_text="Would you like to be notified when major progress is made on the Ethnic Equity and Public Representation Bill, including voting stages, committee debates, and implementation milestones? If you've opted in, we’ll send periodic civic alerts via WhatsApp or SMS so you can follow the bill’s journey.", null=True),
        ),
    ]
