# Generated by Django 5.2.4 on 2025-07-23 13:24

import apps.common.validators.identity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_userprofile_wants_bill_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wants_bill_notifications',
            field=models.BooleanField(blank=True, default=None, help_text='Would you like to be notified when major progress is made on the Ethnic Equity and Public Representation Bill, including voting stages, committee debates, and implementation milestones? If you choose to opt in, we’ll send periodic civic alerts via WhatsApp or SMS so you can follow the bill’s journey.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_opt_in_number',
            field=models.CharField(blank=True, help_text="If you've opted to receive bill updates, please enter a valid WhatsApp number in international E.164 format (e.g., +254712345678). This is where we’ll send civic alerts via WhatsApp or SMS. Leave blank if you prefer not to receive notifications.", max_length=20, validators=[apps.common.validators.identity.validate_phone_e164]),
        ),
    ]
