# Generated by Django 5.2.4 on 2025-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_userprofile_wants_bill_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image_visible',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_profiles/defaults/unisex_kenyan_flag.webp', help_text='Optional profile image. Only visible in your private dashboard. Default image shown if none is uploaded. Never shown publicly and will never be shared.', null=True, upload_to='user_profiles/profile_images/', verbose_name='Profile photo'),
        ),
    ]
