# Generated by Django 5.2.4 on 2025-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_remove_userprofile_profile_image_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False, help_text='Snapshot of profile completion (0–100).'),
        ),
    ]
