# Generated by Django 5.2.4 on 2025-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_userprofile_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_wizard_login_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last time user returned to resume an incomplete profile.', null=True),
        ),
    ]
