# Generated by Django 5.2.4 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceeni_captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiccaptcha',
            name='slug',
            field=models.SlugField(help_text='Unique slug for referencing or analytics', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jumbledconstituencycaptcha',
            name='slug',
            field=models.SlugField(help_text='Unique slug for referencing or analytics', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jumbledcountycaptcha',
            name='slug',
            field=models.SlugField(help_text='Unique slug for referencing or analytics', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jumbledleadercaptcha',
            name='slug',
            field=models.SlugField(help_text='Unique slug for referencing or analytics', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jumbledwardcaptcha',
            name='slug',
            field=models.SlugField(help_text='Unique slug for referencing or analytics', max_length=100, unique=True),
        ),
    ]
