# Generated by Django 5.2.4 on 2025-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceeni_captcha', '0002_alter_civiccaptcha_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalPartyLeaderCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Main question prompt (e.g., trivia, riddle, jumbled phrase)')),
                ('correct_answer', models.CharField(help_text='Expected correct answer (case-insensitive match)', max_length=100)),
                ('hint', models.TextField(blank=True, help_text='Optional hint to assist user in solving the captcha')),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation shown after correct/incorrect answer (for civic learning)')),
                ('difficulty', models.IntegerField(default=1, help_text='Scale from 0 (very easy) to 5 (very hard)')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated keywords like 'elections,leadership,constitution'", max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for referencing or analytics', max_length=100, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Only active captchas will be used during registration or civic flow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Political Party Leader Captcha',
                'verbose_name_plural': 'Political Party Leader Captchas',
            },
        ),
    ]
