# Generated by Django 5.2.4 on 2025-08-10 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('doc_type', models.CharField(choices=[('constitution', 'Constitution'), ('bill', 'Bill'), ('brief', 'Brief'), ('other', 'Other')], default='other', max_length=32)),
                ('source_path', models.TextField(help_text='Original file path or URL')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ceeni_documents.document')),
            ],
            options={
                'ordering': ['document', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('vector', models.BinaryField()),
                ('dim', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='ceeni_documents.section')),
            ],
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('document', 'index'), name='unique_section_per_document_index'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['model'], name='ceeni_docum_model_1bff50_idx'),
        ),
    ]
