# Generated by Django 5.2.4 on 2025-07-18 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Blocked word or nickname (e.g. slurs, gang terms, known abusers)', max_length=64, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this term was added')),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin or staff who added this word (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Nickname',
                'verbose_name_plural': 'Blocked Nicknames',
                'ordering': ['word'],
            },
        ),
    ]
