# Generated by Django 5.2.4 on 2025-07-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockednickname',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_nicknames_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockednickname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blockednickname',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blockednickname',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who first added this term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_nicknames_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockednickname',
            name='word',
            field=models.CharField(help_text='Blocked word or nickname (e.g. slurs, political or ethnic insults)', max_length=64, unique=True),
        ),
    ]
