# Generated by Django 5.2.4 on 2025-07-15 07:59

import user_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(help_text='Short nickname to base the username on', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Phone number in E.164 format (e.g., +254712345678)', max_length=20, unique=True, validators=[user_accounts.models.validate_phone_e164]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(editable=False, help_text='Auto-generated unique username based on nickname', max_length=32, unique=True),
        ),
    ]
