# Generated by Django 5.2.4 on 2025-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(help_text='Short user-friendly name; used to generate username', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(editable=False, help_text='Auto-generated username based on nickname + NanoID', max_length=32, unique=True),
        ),
    ]
